name: "Continuous Integration"

on:
    pull_request:
        branches:
            - "*.x"
    push:
        branches:
            - "*.x"

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-20.04"
        env:
            SYMFONY_REQUIRE: ${{matrix.symfony-require}}
            SYMFONY_DEPRECATIONS_HELPER: ${{matrix.symfony-deprecations-helper}}

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - "7.4"
                dependencies:
                    - "highest"
                stability:
                    - "stable"
                symfony-require:
                    - ""
                symfony-deprecations-helper:
                    - ""
                include:
                    # Tests the lowest set of dependencies
                    -   dependencies: "lowest"
                        stability: "stable"
                        php-version: "7.4"
                        symfony-deprecations-helper: "weak"

                    # Test LTS
                    -   symfony-require: "4.4.*"
                        dependencies: "stable"
                        php-version: "7.4"
                        symfony-deprecations-helper: "weak"

                    # Test against latest Symfony 5.x dev
                    -   symfony-require: "5.*"
                        dependencies: "highest"
                        php-version: "8.0"
                        symfony-deprecations-helper: "weak"

                    # Test against latest Symfony 6.x dev
                    -   symfony-require: "6.*"
                        dependencies: "highest"
                        php-version: "8.0"
                        symfony-deprecations-helper: "weak"

                    # Test against latest Symfony dev
                    -   php-version: "8.1"
                        dependencies: "highest"
                        stability: "dev"
                        symfony-deprecations-helper: "weak"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"
                with:
                    fetch-depth: 2

            -   name: "Install PHP with PCOV"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php-version }}"
                    coverage: "pcov"
                    ini-values: "zend.assertions=1"

            -   name: "Enforce using stable dependencies"
                run: "composer config minimum-stability stable"
                if: "${{ matrix.stability == 'stable' }}"

            -   name: "Install dependencies with Composer"
                uses: "ramsey/composer-install@v1"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"
                    composer-options: "--prefer-dist"

            -   name: "Run PHPUnit"
                run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

            -   name: "Upload coverage file"
                uses: "actions/upload-artifact@v2"
                with:
                    name: "phpunit-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}.coverage"
                    path: "coverage.xml"

    upload_coverage:
        name: "Upload coverage to Codecov"
        runs-on: "ubuntu-20.04"
        needs:
            - "phpunit"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"
                with:
                    fetch-depth: 2

            -   name: "Download coverage files"
                uses: "actions/download-artifact@v2"
                with:
                    path: "reports"

            -   name: "Upload to Codecov"
                uses: "codecov/codecov-action@v2"
                with:
                    directory: reports
